#!/usr/bin/env node
// Generates server/public/tartarus-icons.css, which redraws Font Awesome icons
// with Phosphor's thin-line "Light" weight. Markup keeps its fa-* classes, so
// icons built in JS strings and in third-party app scripts are covered too.
// Icons without a Phosphor match keep rendering as Font Awesome.
//
// Regenerate (needs `npm i @phosphor-icons/web` somewhere resolvable):
//   node backend/script/tartarus-icons.js [path/to/phosphor/light/style.css]

const fs = require('fs')
const path = require('path')

const publicDir = path.resolve(__dirname, '..', 'server', 'public')
const phosphorCss = process.argv[2]
  || path.join(path.dirname(require.resolve('@phosphor-icons/web/package.json')), 'src', 'light', 'style.css')

// Font Awesome name -> Phosphor name, for icons whose names differ.
const ALIASES = {
  'align-left': 'text-align-left',
  'align-center': 'text-align-center',
  'align-right': 'text-align-right',
  'angle-down': 'caret-down',
  'angle-left': 'caret-left',
  'angle-right': 'caret-right',
  'angle-up': 'caret-up',
  'angles-down': 'caret-double-down',
  'angles-left': 'caret-double-left',
  'angles-right': 'caret-double-right',
  'angles-up': 'caret-double-up',
  'chevron-down': 'caret-down',
  'chevron-left': 'caret-left',
  'chevron-right': 'caret-right',
  'chevron-up': 'caret-up',
  'caret-down': 'caret-down',
  'circle-chevron-down': 'caret-circle-down',
  'circle-chevron-up': 'caret-circle-up',
  'circle-chevron-left': 'caret-circle-left',
  'circle-chevron-right': 'caret-circle-right',
  'arrow-down-a-z': 'sort-ascending',
  'arrow-down-z-a': 'sort-descending',
  'arrow-down-wide-short': 'sort-descending',
  'arrow-up-short-wide': 'sort-ascending',
  'arrow-up-wide-short': 'sort-ascending',
  'arrow-rotate-left': 'arrow-counter-clockwise',
  'arrow-rotate-right': 'arrow-clockwise',
  'rotate-left': 'arrow-counter-clockwise',
  'rotate-right': 'arrow-clockwise',
  'rotate': 'arrows-clockwise',
  'arrows-rotate': 'arrows-clockwise',
  'refresh': 'arrows-clockwise',
  'sync': 'arrows-clockwise',
  'arrow-up-right-from-square': 'arrow-square-out',
  'up-right-from-square': 'arrow-square-out',
  'external-link': 'arrow-square-out',
  'square-arrow-up-right': 'arrow-square-up-right',
  'arrow-right-from-bracket': 'sign-out',
  'right-from-bracket': 'sign-out',
  'arrow-right-to-bracket': 'sign-in',
  'right-to-bracket': 'sign-in',
  'arrows-left-right': 'arrows-left-right',
  'up-down-left-right': 'arrows-out-cardinal',
  'bars': 'list',
  'bars-staggered': 'list-dashes',
  'list-ul': 'list-bullets',
  'list-ol': 'list-numbers',
  'list-check': 'list-checks',
  'beer-mug-empty': 'beer-stein',
  'bolt': 'lightning',
  'bolt-lightning': 'lightning',
  'box': 'package',
  'box-open': 'package',
  'box-archive': 'archive',
  'boxes-stacked': 'stack',
  'layer-group': 'stack',
  'circle-check': 'check-circle',
  'square-check': 'check-square',
  'circle-down': 'arrow-circle-down',
  'circle-up': 'arrow-circle-up',
  'circle-exclamation': 'warning-circle',
  'exclamation': 'warning',
  'triangle-exclamation': 'warning',
  'circle-info': 'info',
  'info-circle': 'info',
  'info': 'info',
  'circle-play': 'play-circle',
  'circle-pause': 'pause-circle',
  'circle-stop': 'stop-circle',
  'circle-question': 'question',
  'question-circle': 'question',
  'circle-user': 'user-circle',
  'user-circle': 'user-circle',
  'circle-xmark': 'x-circle',
  'times-circle': 'x-circle',
  'circle-plus': 'plus-circle',
  'circle-minus': 'minus-circle',
  'circle-half-stroke': 'circle-half',
  'clock-rotate-left': 'clock-counter-clockwise',
  'history': 'clock-counter-clockwise',
  'clone': 'copy-simple',
  'paste': 'clipboard',
  'code-branch': 'git-branch',
  'code-commit': 'git-commit',
  'code-compare': 'git-diff',
  'code-fork': 'git-fork',
  'code-merge': 'git-merge',
  'code-pull-request': 'git-pull-request',
  'comments': 'chats',
  'comment': 'chat',
  'comment-dots': 'chat-dots',
  'message': 'chat-centered-text',
  'compress': 'arrows-in',
  'expand': 'arrows-out',
  'maximize': 'arrows-out',
  'minimize': 'arrows-in',
  'down-left-and-up-right-to-center': 'arrows-in',
  'up-right-and-down-left-from-center': 'arrows-out',
  'computer': 'desktop',
  'display': 'monitor',
  'tv': 'television',
  'laptop-code': 'laptop',
  'mobile': 'device-mobile',
  'mobile-screen': 'device-mobile',
  'mobile-screen-button': 'device-mobile',
  'tablet': 'device-tablet',
  'dice-d6': 'cube',
  'cubes': 'cube',
  'ellipsis': 'dots-three',
  'ellipsis-h': 'dots-three',
  'ellipsis-vertical': 'dots-three-vertical',
  'ellipsis-v': 'dots-three-vertical',
  'file-lines': 'file-text',
  'file-alt': 'file-text',
  'file-zipper': 'file-zip',
  'file-shield': 'shield-check',
  'file-circle-plus': 'file-plus',
  'file-export': 'export',
  'file-import': 'download-simple',
  'file-arrow-down': 'file-arrow-down',
  'floppy-disk': 'floppy-disk',
  'save': 'floppy-disk',
  'folder-closed': 'folder-simple',
  'folder-tree': 'tree-structure',
  'sitemap': 'tree-structure',
  'diagram-project': 'flow-arrow',
  'gears': 'gear-six',
  'cog': 'gear',
  'sliders': 'sliders-horizontal',
  'filter': 'funnel',
  'home': 'house',
  'house-chimney': 'house',
  'image-slash': 'image-broken',
  'images': 'images',
  'photo-film': 'film-strip',
  'film': 'film-strip',
  'lock-closed': 'lock',
  'unlock': 'lock-open',
  'unlock-keyhole': 'lock-open',
  'lock-keyhole': 'lock',
  'magnifying-glass': 'magnifying-glass',
  'search': 'magnifying-glass',
  'microchip': 'cpu',
  'memory': 'memory',
  'server': 'hard-drives',
  'network-wired': 'network',
  'ethernet': 'network',
  'paper-plane': 'paper-plane-tilt',
  'pen-to-square': 'note-pencil',
  'edit': 'note-pencil',
  'pen-nib': 'pen-nib',
  'plug-circle-bolt': 'plugs-connected',
  'plug-circle-check': 'plugs-connected',
  'plug-circle-xmark': 'plugs',
  'podcast': 'microphone',
  'microphone-slash': 'microphone-slash',
  'power-off': 'power',
  'qrcode': 'qr-code',
  'route': 'path',
  'ruler-combined': 'ruler',
  'shield-halved': 'shield',
  'shield-alt': 'shield',
  'sort': 'arrows-down-up',
  'sort-down': 'caret-down',
  'sort-up': 'caret-up',
  'table-columns': 'columns',
  'columns': 'columns',
  'table-list': 'table',
  'table-cells': 'grid-four',
  'table-cells-large': 'squares-four',
  'grip': 'dots-six',
  'grip-vertical': 'dots-six-vertical',
  'terminal': 'terminal-window',
  'toggle-on': 'toggle-right',
  'toggle-off': 'toggle-left',
  'trash-can': 'trash',
  'trash-alt': 'trash',
  'video': 'video-camera',
  'video-slash': 'video-camera-slash',
  'wand-magic-sparkles': 'magic-wand',
  'wand-magic': 'magic-wand',
  'magic': 'magic-wand',
  'wifi': 'wifi-high',
  'xmark': 'x',
  'times': 'x',
  'close': 'x',
  'remove': 'x',
  'download': 'download-simple',
  'upload': 'upload-simple',
  'cloud-download': 'cloud-arrow-down',
  'cloud-upload': 'cloud-arrow-up',
  'arrow-down-to-line': 'arrow-line-down',
  'user-gear': 'user-gear',
  'users': 'users',
  'user-group': 'users-three',
  'right-left': 'arrows-left-right',
  'link': 'link-simple',
  'link-slash': 'link-simple-break',
  'up-long': 'arrow-up',
  'down-long': 'arrow-down',
  'left-long': 'arrow-left',
  'right-long': 'arrow-right',
  'location-dot': 'map-pin',
  'location-pin': 'map-pin',
  'earth-americas': 'globe-hemisphere-west',
  'globe': 'globe',
  'hard-drive': 'hard-drive',
  'hdd': 'hard-drive',
  'heart': 'heart',
  'thumbtack': 'push-pin',
  'tag': 'tag',
  'tags': 'tag',
  'bookmark': 'bookmark-simple',
  'brain': 'brain',
  'robot': 'robot',
  'newspaper': 'newspaper',
  'rss': 'rss',
  'eye-slash': 'eye-slash',
  'circle-notch': 'circle-notch',
  'spinner': 'spinner',
  'stop': 'stop',
  'pause': 'pause',
  'forward': 'fast-forward',
  'backward': 'rewind',
  'keyboard': 'keyboard',
  'hand': 'hand',
  'flask': 'flask',
  'toolbox': 'toolbox',
  'wrench': 'wrench',
  'screwdriver-wrench': 'wrench',
  'hammer': 'hammer',
  'calendar': 'calendar-blank',
  'calendar-days': 'calendar',
  'chart-line': 'chart-line',
  'chart-bar': 'chart-bar',
  'chart-pie': 'chart-pie',
  'gauge': 'gauge',
  'gauge-high': 'gauge',
  'square-plus': 'plus-square',
  'square-minus': 'minus-square',
  'square-xmark': 'x-square',
  'square-up-right': 'arrow-square-up-right',
  'eraser': 'eraser',
  'scissors': 'scissors',
  'crop': 'crop',
  'camera': 'camera',
  'square': 'square',
  'star': 'star',
  'bell': 'bell',
  'bell-slash': 'bell-slash',
  'envelope': 'envelope-simple',
  'inbox': 'tray',
  'at': 'at',
  'hashtag': 'hash',
  'percent': 'percent',
  'dollar-sign': 'currency-dollar',
  'battery-full': 'battery-full',
  'sun': 'sun',
  'moon': 'moon',
  'cloud': 'cloud',
  'fire': 'fire',
  'leaf': 'leaf',
  'skull': 'skull',
  'ghost': 'ghost',
  'gift': 'gift',
  'trophy': 'trophy',
  'flag': 'flag',
  'puzzle-piece': 'puzzle-piece',
  'shuffle': 'shuffle',
  'repeat': 'repeat',
  'volume-high': 'speaker-high',
  'volume-low': 'speaker-low',
  'volume-xmark': 'speaker-x',
  'music': 'music-note',
  'headphones': 'headphones',
  'book': 'book',
  'book-open': 'book-open',
  'graduation-cap': 'graduation-cap',
  'lightbulb': 'lightbulb',
  'water': 'waves',
  'wave-square': 'wave-square',
  // brands
  'apple': 'apple-logo',
  'android': 'android-logo',
  'linux': 'linux-logo',
  'windows': 'windows-logo',
  'github': 'github-logo',
  'gitlab': 'gitlab-logo',
  'git-alt': 'git-branch',
  'discord': 'discord-logo',
  'x-twitter': 'x-logo',
  'square-x-twitter': 'x-logo',
  'twitter': 'twitter-logo',
  'youtube': 'youtube-logo',
  'google': 'google-logo',
  'docker': 'cube',
  'python': 'file-py',
  'js': 'file-js',
  'npm': 'package',
  'slack': 'slack-logo',
  'reddit': 'reddit-logo',
  'telegram': 'telegram-logo',
  'instagram': 'instagram-logo',
  'facebook': 'facebook-logo',
  'linkedin': 'linkedin-logo',
  'chrome': 'google-chrome-logo',
  'figma': 'figma-logo',
  'openai': 'open-ai-logo',
}

const BRANDS = new Set(['apple', 'android', 'linux', 'windows', 'github', 'gitlab', 'git-alt', 'discord', 'x-twitter',
  'square-x-twitter', 'twitter', 'youtube', 'google', 'docker', 'python', 'js', 'npm', 'slack', 'reddit', 'telegram',
  'instagram', 'facebook', 'linkedin', 'chrome', 'figma', 'openai'])

const faCss = fs.readFileSync(path.join(publicDir, 'css', 'all.css'), 'utf8')
const faNames = new Set()
for (const m of faCss.matchAll(/^\.fa-([a-z0-9-]+) \{\n\s+--fa:/gm)) faNames.add(m[1])
// Used by the UI but missing from Font Awesome Free, so they render blank without a mapping.
for (const name of ['image-slash', 'lock-closed']) faNames.add(name)

const phCss = fs.readFileSync(phosphorCss, 'utf8')
const phGlyphs = new Map()
for (const m of phCss.matchAll(/\.ph-light\.ph-([a-z0-9-]+):before \{\s*content: "(\\[0-9a-f]+)";/g)) phGlyphs.set(m[1], m[2])

const resolve = (fa) => {
  const candidates = []
  if (ALIASES[fa]) candidates.push(ALIASES[fa])
  candidates.push(fa)
  let m
  if ((m = fa.match(/^circle-(.+)$/))) candidates.push(`${m[1]}-circle`)
  if ((m = fa.match(/^square-(.+)$/))) candidates.push(`${m[1]}-square`)
  return candidates.find((c) => phGlyphs.has(c))
}

const rules = []
const missing = []
for (const fa of [...faNames].sort()) {
  const ph = resolve(fa)
  if (!ph) { missing.push(fa); continue }
  const scope = BRANDS.has(fa) ? ':is(.fab, .fa-brands)' : ':is(.fas, .far, .fa, .fa-solid, .fa-regular, .fa-classic)'
  rules.push(`${scope}.fa-${fa}::before { content: "${phGlyphs.get(ph)}" !important; }`)
}

const header = `/* Generated by backend/script/tartarus-icons.js - do not edit by hand.
 * Redraws Font Awesome icons with Phosphor Light (MIT, https://phosphoricons.com).
 * ${rules.length} icons mapped; unmapped icons keep their Font Awesome glyph. */
`
const mappedSelector = [...faNames].filter((fa) => resolve(fa)).map((fa) => `.fa-${fa}`)
const base = `:is(.fas, .far, .fab, .fa, .fa-solid, .fa-regular, .fa-brands, .fa-classic):is(${mappedSelector.join(', ')})::before {
  font-family: "Phosphor-Light" !important;
  font-weight: normal !important;
  font-style: normal !important;
}
`
fs.writeFileSync(path.join(publicDir, 'tartarus-icons.css'), header + base + rules.join('\n') + '\n')
console.log(`tartarus-icons: mapped ${rules.length} of ${faNames.size} Font Awesome icons (${missing.length} kept as Font Awesome)`)
